name: CICD

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

  release:
    types: [created]


jobs:
  build:
    uses: artagame/githubactions/.github/workflows/build.yml@main
    with:
      solution_name:  ALMLab
      solution_exported_folder: out/exported/
      solution_folder: out/solutions/
      solution_target_folder: solutions/
    secrets:
      ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
      CLIENT_ID: ${{ secrets.BUILD_CLIENT_ID }}
      TENANT_ID: ${{ secrets.BUILD_TENANT_ID }}
      ClIENT_SECRET: ${{ secrets.BUILD_ClIENT_SECRET }}
    

  release:
    needs: [ build ]
    uses: artagame/githubactions/.github/workflows/release.yml@main
    with:
      solution_name:  ALMLab
      solution_shipping_folder: out/ship/
      solution_outbound_folder: out/solutions/
      solution_source_folder: solutions/
      solution_release_folder: out/release
    secrets:
      BUILD_ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
      BUILD_CLIENT_ID: ${{ secrets.BUILD_CLIENT_ID }}
      BUILD_TENANT_ID: ${{ secrets.BUILD_TENANT_ID }}
      BUILD_ClIENT_SECRET: ${{ secrets.BUILD_ClIENT_SECRET }}
      SIT_ENVIRONMENT_URL: ${{ secrets.SIT_ENVIRONMENT_URL }}
      SIT_CLIENT_ID: ${{ secrets.SIT_CLIENT_ID }}
      SIT_TENANT_ID: ${{ secrets.SIT_TENANT_ID }}
      SIT_ClIENT_SECRET: ${{ secrets.SIT_ClIENT_SECRET }}
      UAT_ENVIRONMENT_URL: ${{ secrets.UAT_ENVIRONMENT_URL }}
      UAT_CLIENT_ID: ${{ secrets.UAT_CLIENT_ID }}
      UAT_TENANT_ID: ${{ secrets.UAT_TENANT_ID }}
      UAT_ClIENT_SECRET: ${{ secrets.UAT_ClIENT_SECRET }}
      PROD_ENVIRONMENT_URL: ${{ secrets.PROD_ENVIRONMENT_URL }}
      PROD_CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
      PROD_TENANT_ID: ${{ secrets.PROD_TENANT_ID }}
      PROD_ClIENT_SECRET: ${{ secrets.PROD_ClIENT_SECRET }}