name: CICD

run-name: Triggered by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

  release:
    types: [created]


jobs:
  build:
    uses: artagame/githubactions/.github/workflows/build.yml@main
    with:
      solution_name:  ALMLab
      solution_exported_folder: out/exported/
      solution_folder: out/solutions/
      solution_target_folder: solutions/
    environment: dev
    

  release:
    needs: [ build ]
    uses: artagame/githubactions/.github/workflows/release.yml@main
    with:
      solution_name:  ALMLab
      solution_shipping_folder: out/ship/
      solution_outbound_folder: out/solutions/
      solution_source_folder: solutions/
      solution_release_folder: out/release
